server.port=8761
spring.application.name=EUREKA-SERVER
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
monitoring.expected-services=GATEWAY-SERVICE,CONTENT-SERVICE,COMMUNITY-SERVICE,TRACKING-SERVICE,DASHBOARD-SERVICE
