# src/main/resources/application.yml
server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.85
  instance:
    hostname: localhost

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO