apiVersion: v1
kind: Secret
metadata:
  name: activities-secret
type: Opaque
stringData:
  # IMPORTANT: en prod, gère ça via un vrai secret manager
  SPRING_DATASOURCE_USERNAME: "cognivita"
  SPRING_DATASOURCE_PASSWORD: "password"

