sonar.projectKey=cognivita-backend
sonar.projectName=COGNIVITA Backend
sonar.projectVersion=1.0

sonar.sources=user-service1/src/main/java,gateway-service/src/main/java,eureka-service/src/main/java,config-server-service/src/main/java
sonar.tests=user-service1/src/test/java,gateway-service/src/test/java

sonar.java.binaries=user-service1/target/classes,gateway-service/target/classes,eureka-service/target/classes,config-server-service/target/classes

sonar.sourceEncoding=UTF-8
sonar.language=java
sonar.java.source=21
