spring.application.name=user-service1
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.fail-fast=false
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=najjaaali3@gmail.com
spring.mail.password=aajpqlmqgrikjudh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ?? Google OAuth2 ?????????????????????????????????
spring.security.oauth2.client.registration.google.client-id=42425832618-80h7c5hqh0st1p3438uoi7ennoslq7a4.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-name=Google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email
# ?? Cloudinary
cloudinary.cloud-name=db5fae4od
cloudinary.api-key=712199524523955
cloudinary.api-secret=Hweu7rBplKTmDs9VXYAObnOVZZM

cognivita.app.cors.allowed-origins=http://localhost:4200
//Hweu7rBplKTmDs9VXYAObnOVZZM