server:
  port: 8081

spring:
  application:
    name: medical-records-service

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:medical_records_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          default_constraint_mode: NO_CONSTRAINT
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: monta.bellakhal10@gmail.com
    password: yjxfilvgruxdrbhc
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
        debug: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

report:
  email:
    from: monta.bellakhal10@gmail.com
    doctor: monta.bellakhal10@gmail.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true

family-tree:
  base-url: http://localhost:8083

user-service:
  base-url: ${USER_SERVICE_URL:http://localhost:9090}

cnn:
  service:
    url: ${CNN_SERVICE_URL:http://localhost:8000}

medication-adherence:
  base-url: http://localhost:8086