apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  namespace: cognivita
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8093"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z mysql 3306; do sleep 2; done"]
        - name: wait-for-eureka
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z eureka-server 8761; do sleep 2; done"]
      containers:
        - name: content-service
          image: medsadek/content-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8093
          env:
            - name: SERVER_PORT
              value: "8093"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/forum_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: cognivita
spec:
  type: ClusterIP
  selector:
    app: content-service
  ports:
    - name: http
      port: 8093
      targetPort: 8093
