package com.alzheimer.medicalrecords.entity;

public enum EventType {
    RECORD_CREATED,
    RECORD_UPDATED,
    MEDICAL_RECORD_UPDATED,
    RISK_FACTOR_ADDED,
    RISK_FACTOR_UPDATED,
    RISK_FACTOR_REMOVED,
    PREVENTION_ACTION_ADDED,
    PREVENTION_ACTION_UPDATED,
    PREVENTION_ACTION_COMPLETED,
    PREVENTION_ACTION_CANCELLED,
    RISK_SCORE_UPDATED,
    RECOMMENDATION_GENERATED,
    APPOINTMENT_SCHEDULED,
    APPOINTMENT_COMPLETED,
    APPOINTMENT_MISSED,
    APPOINTMENT_CANCELLED,
    MEDICATION_INTERACTION_ALERT
}
