server.port=8088
spring.application.name=GATEWAY-SERVICE

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true

spring.cloud.gateway.routes[0].id=community-service-route
spring.cloud.gateway.routes[0].uri=lb://COMMUNITY-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/communities/**

spring.cloud.gateway.routes[1].id=post-service-route
spring.cloud.gateway.routes[1].uri=lb://CONTENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/posts/**

spring.cloud.gateway.routes[2].id=comment-service-route
spring.cloud.gateway.routes[2].uri=lb://CONTENT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/comments/**

spring.cloud.gateway.routes[3].id=vote-service-route
spring.cloud.gateway.routes[3].uri=lb://CONTENT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/votes/**

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
