spring.application.name=config-server-service
server.port=8888

spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:C:/Users/user/Downloads/Alzheimer-Detection-System/Alzheimer-Detection-System/Backend/config-repo

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=health,info
