spring.application.name=gateway-service
server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route → user-service1
spring.cloud.gateway.routes[0].id=user-service1
spring.cloud.gateway.routes[0].uri=lb://user-service1
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always
