apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - mysql-secret.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - pi-deployment.yaml
  - pi-service.yaml
  - plansuivi-deployment.yaml
  - plansuivi-service.yaml
