apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi
  namespace: cognivita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi
  template:
    metadata:
      labels:
        app: pi
    spec:
      containers:
        - name: pi
          image: lozzaaa/pi-rdv-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "8091"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: cognivita-config
                  key: EUREKA_DEFAULT_ZONE
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: cognivita-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SPRING_DATASOURCE_PASSWORD
          readinessProbe:
            httpGet:
              path: /rdv/actuator/health
              port: 8091
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /rdv/actuator/health
              port: 8091
            initialDelaySeconds: 45
            periodSeconds: 15
